name: imithon
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <4.0.0"  # Ensure this range covers Dart 3.x (change it as needed)

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - imithon/A.jpg